/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "stdint.h"

#define RCC_BASE 0x40021000
#define APB2ENR_offset 0x18
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + APB2ENR_offset)
#define GPIOA_BASE (0x40010800)
#define GPIOB_BASE (0x40010C00)
#define CRL_offset 0x00
#define CRH_offset 0x04
#define IDR_offset 0x08
#define ODR_offset 0x0c
uint32_t GPIOADDRESS[]={GPIOA_BASE,GPIOB_BASE};
typedef enum {
	GPIOA,GPIOB
}GPIO;

typedef struct{
	uint8_t prev;
	uint8_t curr;
}button;
// mode = 0 >> input + floating
//mode = 1 >> output + push pull
void GPIO_init(GPIO index,uint8_t pin,char mode){
	if(pin < 8){
		*(volatile uint32_t*)(GPIOADDRESS[index]+CRL_offset) &= ~(0xF << (pin*4));
		if(mode == 0){
			*(volatile uint32_t*)(GPIOADDRESS[index]+CRL_offset) |= (0x4 << (pin*4));
		}
		else{
			*(volatile uint32_t*)(GPIOADDRESS[index]+CRL_offset) |= (0x1<<(pin*4));
			*(volatile uint32_t*)(GPIOADDRESS[index]+ODR_offset) &= ~(1<<pin);
		}
	}
	else {
		*(volatile uint32_t*)(GPIOADDRESS[index]+CRH_offset) &= ~(0xF<<((pin-8)*4));
		if(mode == 0){
			*(volatile uint32_t*)(GPIOADDRESS[index]+CRH_offset) |= (0x4<<((pin-8)*4));
		}
		else{
			*(volatile uint32_t*)(GPIOADDRESS[index]+CRH_offset) |= (0x1<<((pin-8)*4));
			*(volatile uint32_t*)(GPIOADDRESS[index]+ODR_offset) &= ~(1<<pin);
		}
	}

}
void clock_init(){
	RCC_APB2ENR |= (1<<2); //enable clock for port A and B
	RCC_APB2ENR |= (1<<3);
}
int GPIOREAD_M(GPIO index , uint8_t pin){
	return (((*(volatile uint32_t*)(GPIOADDRESS[index]+IDR_offset)) & (1<<pin))>>pin);  //return 1 as pressed or 0 as not pressed
}
void GPIOTOGGLE(GPIO index , uint8_t pin ){
	*(volatile uint32_t*)(GPIOADDRESS[index]+ODR_offset) ^= (1<<pin);
}
int GPIOREAD_S(GPIO index , uint8_t pin, button* b){
	int result;
	b->curr=((*(volatile uint32_t*)(GPIOADDRESS[index]+IDR_offset)) & (1<<pin))>>pin;
	if(b->prev==1 && b->curr ==0){
		result =1;
	}
	else{
		result = 0;
	}
	b->prev=b->curr;
	return result;
}
int main(void)
{
	button b;
	b.prev=1;
	/* Loop forever */
	clock_init();
	GPIO_init(GPIOA,1,0);
	GPIO_init(GPIOA,13,0);
	GPIO_init(GPIOB,13,1);
	GPIO_init(GPIOB,1,1);
	while(1){
		if(GPIOREAD_S(GPIOA,1,&b)){
			GPIOTOGGLE(GPIOB, 1);
		}
		if(GPIOREAD_M(GPIOA,13)==1){
			GPIOTOGGLE(GPIOB, 13);
		}
		for(volatile int i=0;i<1024;i++){
			;
		}
	}
}
